timezone: Europe/Berlin
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - assets/config.rb
  - assets/sass
markdown_ext: "md"
kramdown:
  input: GFM
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "post"
